version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: 
      - start-dev
      - --import-realm
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge